// Lab 8 report — content only. Boilerplate lives in ../report-lib.js
//   cd labs && npm install         (once)
//   node lab8/build_report.js
const { makeReport } = require("../report-lib");

// Screenshot filenames (timestamped) mapped to tasks.
const S = {
  t1_policy:   "Screenshot 2026-07-08 at 10.41.52.png", // set policies + -L -v (FORWARD DROP)
  t1_drop:     "Screenshot 2026-07-08 at 10.42.27.png", // host2: ping 10.9.0.5 fail, ping .11 ok
  t1_accept:   "Screenshot 2026-07-08 at 10.49.15.png", // host2: ping 10.9.0.5 ok (ttl=63)
  t2a_rule:    "Screenshot 2026-07-08 at 11.11.36.png", // -A INPUT -s .5 DROP + list
  t2a_ping:    "Screenshot 2026-07-08 at 11.11.48.png", // host1 ping router: 100% loss
  t2b:         "Screenshot 2026-07-08 at 11.15.43.png", // -A OUTPUT -d .5 + ping: Operation not permitted
  t4:          "Screenshot 2026-07-08 at 11.21.12.png", // -L --line-number + -D INPUT 1 + list empty
  t5:          "Screenshot 2026-07-08 at 11.22.26.png", // -L + -F + -L empty
  t6_rule:     "Screenshot 2026-07-08 at 11.25.43.png", // -P INPUT DROP + accept dport 23 + -L -v
  t6_telnet:   "Screenshot 2026-07-08 at 11.25.55.png", // telnet ok + ping fail
  t6_ping:     "Screenshot 2026-07-08 at 11.27.08.png", // clean host2 ping router: 100% loss
  t7:          "Screenshot 2026-07-08 at 11.30.39.png", // dig baseline + rule + dig timeout vs local ok
  t8_rule:     "Screenshot 2026-07-08 at 11.32.50.png", // delete dns rule + add icmp echo-request DROP
  t8_in:       "Screenshot 2026-07-08 at 11.33.01.png", // host2 ping router: 100% loss
  t8_out:      "Screenshot 2026-07-08 at 11.33.36.png", // router ping host2: success
  t9_router:   "Screenshot 2026-07-08 at 11.37.00.png", // conntrack rule + router telnet host3 ok
  t9_host3:    "Screenshot 2026-07-08 at 11.39.00.png", // host3 telnet router: Trying... ^C (blocked)
  t10:         "Screenshot 2026-07-08 at 11.40.35.png", // save / flush / restore
};

makeReport({
  labDir: __dirname,
  outName: "Lab8_Firewall_Report.docx",
  title: "COMP8677 — Lab 8 Report",
  subtitle: "Firewall with iptables",
  // no author (unsigned)
  body: ({ P, H1, H2, code, figure, spacer }) => [
    // ===== Objective / setup =====
    H1("1. Objective and Setup"),
    P("This lab practises Linux firewall configuration with iptables in the SEED-Ubuntu Docker environment. A docker-compose file builds a small routed network with two subnets connected by a router:"),
    ...code(
`Internal 192.168.60.0/24            External 10.9.0.0/24
  Host1 192.168.60.5                  HostA 10.9.0.5
  Host2 192.168.60.6
  Host3 192.168.60.7
             \\                       /
              Router  192.168.60.11 / 10.9.0.11  (ip_forward = 1)`
    ),
    P("The router forwards traffic between the two networks (net.ipv4.ip_forward = 1) and is the default gateway for the three internal hosts. Every firewall rule below is applied on the router. All commands are run as root inside the containers (entered with docksh), so sudo is not needed. iptables uses three built-in chains of the default filter table: INPUT (packets destined to this host), OUTPUT (packets generated by this host), and FORWARD (packets merely routed through this host). The general rule form is:"),
    ...code("iptables -t TABLE -A CHAIN  <match conditions>  -j ACTION"),
    P("where -A appends, -D deletes, -I inserts, -P sets the chain's default policy, and the default table is filter when -t is omitted."),

    // ===== Task 1 =====
    H1("2. Task 1 — Default Policy for the FORWARD Chain"),
    P("The three chain policies were set on the router, with FORWARD defaulting to DROP:"),
    ...code(
`# router
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP
iptables -L -v`
    ),
    ...figure(S.t1_policy, "Figure 2.1 — Router chain policies. FORWARD policy is DROP; INPUT and OUTPUT are ACCEPT.", 560),
    P("From Host2 (192.168.60.6) two pings were then issued — one to a host on the other network and one to the router itself:"),
    ...figure(S.t1_drop, "Figure 2.2 — With FORWARD = DROP: ping 10.9.0.5 gives 100% packet loss, but ping 192.168.60.11 (the router) succeeds.", 520),
    P("Observation: ping 10.9.0.5 fails (100% loss) while ping 192.168.60.11 succeeds. The reason is which chain each packet traverses on the router. A packet from Host2 to 10.9.0.5 must be routed across the router from one network to the other, so it is handled by the FORWARD chain — which defaults to DROP — and is discarded. A packet from Host2 to 192.168.60.11 is destined to the router itself, so it is handled by the INPUT chain (policy ACCEPT) and never touches FORWARD; the reply comes back normally."),
    P("The FORWARD policy was then changed to ACCEPT and the cross-network ping repeated:"),
    ...code(
`# router
iptables -P FORWARD ACCEPT`
    ),
    ...figure(S.t1_accept, "Figure 2.3 — After FORWARD = ACCEPT: ping 10.9.0.5 now succeeds (note ttl=63, decremented by one hop through the router).", 520),
    P("Now the ping succeeds because the router forwards the packets. A detail confirming this: the reply TTL is 63 (Figure 2.3) rather than 64 seen when pinging the router directly (Figure 2.2) — the missing hop is the router decrementing the TTL as it forwards the packet, which proves the traffic really was routed (FORWARD path) rather than answered locally."),

    // ===== Task 2 =====
    H1("3. Task 2 — Blocking a Specific IP Address"),
    P("This task blocks traffic by IP in both directions, using Host1 (192.168.60.5) as the target IP1."),
    H2("3.1  Blocking packets FROM an IP (INPUT chain, -s)"),
    ...code(
`# router
iptables -A INPUT -s 192.168.60.5 -j DROP
iptables -L INPUT --line-number`
    ),
    ...figure(S.t2a_rule, "Figure 3.1 — INPUT rule dropping all packets sourced from host1 (192.168.60.5).", 560),
    P("From Host1, pinging the router now fails:"),
    ...figure(S.t2a_ping, "Figure 3.2 — Host1 → router ping: 100% packet loss (silently dropped).", 520),
    P("Observation: 100% packet loss with no error message. Host1's echo-request does reach the router, but the INPUT rule drops it before the router can respond, so no reply is ever generated. Because the packet is dropped (not rejected), Host1 receives nothing at all and simply times out."),
    H2("3.2  Blocking packets TO an IP (OUTPUT chain, -d)"),
    P("The INPUT rule was removed, then a rule was added to drop packets destined to Host1, and the router itself pinged Host1:"),
    ...code(
`# router
iptables -D INPUT -s 192.168.60.5 -j DROP
iptables -A OUTPUT -d 192.168.60.5 -j DROP
ping -c 3 192.168.60.5`
    ),
    ...figure(S.t2b, "Figure 3.3 — OUTPUT rule dropping packets to host1; the router's ping fails with \"sendmsg: Operation not permitted\".", 540),
    P("Observation: the ping fails immediately with ping: sendmsg: Operation not permitted. This differs from the INPUT case: here the packet is dropped on the way out of the router, in the OUTPUT chain, before it is even sent on the wire. The kernel refuses the local send, so ping reports the error directly rather than timing out. In short — Section 3.1 blocks \"others coming in\", Section 3.2 blocks \"us going out\", and the difference in symptom (silent loss vs. Operation not permitted) reflects where the packet dies."),

    // ===== Task 3 =====
    H1("4. Task 3 — Listing All Rules"),
    P("Rules of the filter table are listed with iptables -L; adding --line-number prints an index for each rule, which is later used to delete a rule by position:"),
    ...code(
`# router
iptables -L
iptables -L --line-number`
    ),
    P("The listings used throughout this report (e.g. Figures 3.1 and 5.1) show both forms: the plain chain listing and the numbered listing with a num column. iptables -L defaults to the filter table (equivalent to iptables -t filter -L)."),

    // ===== Task 4 =====
    H1("5. Task 4 — Deleting a Rule by Index"),
    P("Deleting a specific rule is a two-step process: list with indices, then delete by index."),
    ...code(
`# router
iptables -L INPUT --line-number
iptables -D INPUT 1
iptables -L INPUT --line-number`
    ),
    ...figure(S.t4, "Figure 5.1 — Before: INPUT rule 1 exists; after iptables -D INPUT 1 the chain is empty.", 560),
    P("Observation: the numbered listing shows rule 1 before deletion and an empty INPUT chain afterwards, confirming the rule was removed. Deleting by index is convenient, but indices renumber after each deletion — so when removing several rules, delete from the highest index downward (or re-list between deletions)."),

    // ===== Task 5 =====
    H1("6. Task 5 — Flushing All Rules in a Table"),
    ...code(
`# router
iptables -L          # OUTPUT still holds a leftover DROP rule
iptables -F
iptables -L          # all chains empty`
    ),
    ...figure(S.t5, "Figure 6.1 — iptables -F flushes every rule in the filter table; all three chains are empty afterwards.", 540),
    P("Observation: a single iptables -F removes every rule from all chains of the filter table at once (unlike -D, which removes one rule). Note that -F clears rules only — it does not change the chains' default policies. If a policy had been set to DROP, flushing would leave that DROP policy in force with no accept rules, locking everything out; here all policies were ACCEPT, so connectivity is fully restored."),

    // ===== Task 6 =====
    H1("7. Task 6 — Drop All Incoming Connections Except Telnet"),
    P("A whitelist firewall was built on the router: default-deny on INPUT, with a single rule permitting inbound telnet (TCP port 23)."),
    ...code(
`# router
iptables -P INPUT DROP
iptables -A INPUT -p tcp --dport 23 -j ACCEPT
iptables -L -v`
    ),
    ...figure(S.t6_rule, "Figure 7.1 — INPUT policy DROP with one ACCEPT rule for tcp dpt:telnet.", 560),
    P("From Host2, telnet and ping to the router were compared:"),
    ...figure(S.t6_telnet, "Figure 7.2 — telnet 192.168.60.11 succeeds (login prompt reached), while an ICMP ping to the router gives 100% loss.", 420),
    ...figure(S.t6_ping, "Figure 7.3 — Clean test from Host2's own shell: ping to the router is 100% loss.", 500),
    P("Observation: telnet succeeds but ping fails. The telnet SYN matches the explicit --dport 23 ACCEPT rule, so the connection is allowed. The ICMP echo-request matches no rule, so it falls through to the INPUT default policy — DROP — and is discarded. This illustrates the default-deny (whitelist) model: block everything, then open specific ports. A packet only reaches the default policy when no earlier rule has decided its fate. Afterwards the rules were flushed and the INPUT policy restored to ACCEPT."),

    // ===== Task 7 =====
    H1("8. Task 7 — Drop Outgoing DNS Requests to 8.8.8.8"),
    P("DNS uses UDP port 53. To block only queries sent to the public resolver 8.8.8.8, a rule on the OUTPUT chain matches protocol UDP, destination port 53, and destination address 8.8.8.8:"),
    ...code(
`# router
dig @8.8.8.8 www.uwindsor.ca +short      # baseline: works
iptables -A OUTPUT -p udp --dport 53 -d 8.8.8.8 -j DROP
dig @8.8.8.8 www.uwindsor.ca             # now blocked
dig www.uwindsor.ca                      # local resolver still works`
    ),
    ...figure(S.t7, "Figure 8.1 — Baseline dig to 8.8.8.8 returns 137.207.71.197; after the rule, dig @8.8.8.8 times out, while dig via the default resolver (127.0.0.11) still succeeds.", 470),
    P("Observation: after the rule is installed, dig @8.8.8.8 fails with \"connection timed out; no servers could be reached\", because its query to 8.8.8.8:53/udp matches the DROP rule. In contrast, dig www.uwindsor.ca still succeeds — its query goes to the system's default resolver (SERVER: 127.0.0.11, the Docker embedded DNS), which does not match the rule. Two confirming details: the -L -v listing resolves 8.8.8.8 to dns.google, showing the rule targets exactly that server; and only queries aimed at 8.8.8.8 are blocked, leaving normal name resolution unaffected. The rule was then deleted."),

    // ===== Task 8 =====
    H1("9. Task 8 — Block Incoming Ping Requests"),
    P("To make the router unreachable by ping (as many production servers are configured), inbound ICMP echo-request packets are dropped:"),
    ...code(
`# router
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
iptables -L -v`
    ),
    ...figure(S.t8_rule, "Figure 9.1 — INPUT rule dropping ICMP echo-request (added after removing the Task 7 DNS rule).", 560),
    ...figure(S.t8_in, "Figure 9.2 — Host2 → router ping: 100% packet loss (echo-request dropped on INPUT).", 500),
    P("Crucially, the rule matches only echo-request, not echo-reply, so the router can still ping others itself:"),
    ...figure(S.t8_out, "Figure 9.3 — Router → Host2 ping succeeds, demonstrating the one-way effect.", 500),
    P("Observation: others cannot ping the router (their echo-request is dropped on INPUT, Figure 9.2), yet the router can still ping others (Figure 9.3). This one-way behaviour follows from matching only echo-request: the router's outbound probes are echo-requests on the OUTPUT path (unaffected), and the replies it receives are echo-replies (which do not match the rule). The rule was then removed."),

    // ===== Task 9 =====
    H1("10. Task 9 — Stateful Firewall with conntrack"),
    P("The goal is to block all connections initiated by others while still allowing replies to connections the router itself initiates. This is done with the connection-tracking (conntrack) module, permitting only packets that belong to an already-established or related connection:"),
    ...code(
`# router
iptables -P INPUT DROP
iptables -A INPUT -p tcp -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -L -v`
    ),
    P("Two telnet directions were then tested. First, the router initiates a telnet to Host3 (192.168.60.7):"),
    ...figure(S.t9_router, "Figure 10.1 — conntrack rule in place (INPUT policy DROP). The router's outbound telnet to Host3 succeeds and reaches the login prompt.", 470),
    P("Second, Host3 initiates a telnet back to the router:"),
    ...figure(S.t9_host3, "Figure 10.2 — Host3 → router telnet hangs at \"Trying 192.168.60.11...\" and must be cancelled (Ctrl+C): the connection is blocked.", 520),
    P("Observation: the router → Host3 session succeeds directly, while the Host3 → router session hangs and fails. Explanation by connection state:"),
    ...code(
`Direction            First packet on router INPUT   ctstate   Result
router -> Host3      SYN-ACK reply comes back        ESTABLISHED  accepted (success)
Host3  -> router     SYN arrives                     NEW          no match -> policy DROP (blocked)`
    ),
    P("When the router initiates the connection, its SYN leaves via OUTPUT (policy ACCEPT) and the returning SYN-ACK belongs to an ESTABLISHED connection, so it matches the accept rule and enters. When Host3 initiates, its SYN arriving at the router's INPUT chain is a NEW connection — it matches neither ESTABLISHED nor RELATED, so it falls to the default DROP and the handshake never completes. This \"outbound-only\" posture (--ctstate ESTABLISHED,RELATED) is the standard default of most host and enterprise firewalls. The rules were then flushed and INPUT policy restored to ACCEPT."),

    // ===== Task 10 =====
    H1("11. Task 10 — Saving and Restoring Firewall Rules"),
    P("iptables rules can be exported to a text file and reloaded in bulk:"),
    ...code(
`# router
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP   # a rule to save
iptables-save > myiptables.rules
iptables -F                # flush -> chain empty
iptables-restore < myiptables.rules
iptables -L                # rule is back`
    ),
    ...figure(S.t10, "Figure 11.1 — After iptables-save and a flush the INPUT chain is empty; iptables-restore brings the echo-request DROP rule back.", 470),
    P("Observation: after the flush the INPUT chain is empty, and after iptables-restore the saved echo-request DROP rule reappears exactly as before — confirming the save/restore round-trip. In production, iptables-save / iptables-restore are used to back up rule sets and to load them automatically at boot."),

    // ===== Conclusion =====
    H1("12. Conclusion"),
    P("All ten tasks were completed on the router VM. The exercises demonstrated the three iptables chains and how a packet's relationship to the host selects its chain (Task 1); source- and destination-based blocking and the different symptoms of INPUT vs. OUTPUT drops (Task 2); listing, deleting by index, and flushing rules (Tasks 3–5); a default-deny whitelist that permits only telnet (Task 6); precise multi-condition matching to block a single DNS server (Task 7); dropping only ICMP echo-request for a one-way ping block (Task 8); a stateful, outbound-only firewall using conntrack (Task 9); and backing up and restoring rule sets (Task 10). Together these show how iptables, built on the kernel's Netfilter hooks, implements both stateless packet filtering and stateful connection tracking."),
  ],
});
